name = "Price List Generator"
client_id = "6b5a565d7969924d403aa57f66a1cfea"
application_url = "https://price-list-generator.onrender.com"

[build]
dev_store_url = "cycle1-test.myshopify.com"

[auth]
redirect_urls = ["https://price-list-generator.onrender.com/auth/callback"]

[webhooks]
api_version = "2025-01"

[embedded]
enabled = true
